apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        
        image: 703216717940.dkr.ecr.us-east-1.amazonaws.com/gitops-webapp:frontend-56244ab17d9b4dcf620445edb12c5ce118b8fe75
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "/api"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80