
# name: Frontend CI/CD
# on:
#   push:
#     paths:
#       - 'frontend/**'        
#       - 'k8s/**'             
#       - '!k8s/frontend.yaml'
#     branches: [ main ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}

#       # ------------ ---
#       - name: SonarCloud Scan
#         uses: SonarSource/sonarqube-scan-action@v3
#         continue-on-error: true
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         with:
#           args: >
#             -Dsonar.projectKey=Nabilaebrahim_fproject
#             -Dsonar.organization=nabilaebrahim
#             -Dsonar.sources=frontend/
#       # ------------------------

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ vars.AWS_REGION }}

#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v1

#       - name: Build and Push Frontend Image
#         env:
#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
#           IMAGE_TAG: ${{ github.sha }} 
#         run: |

        
          
#           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:frontend-$IMAGE_TAG ./frontend
#           docker push $ECR_REGISTRY/$ECR_REPOSITORY:frontend-$IMAGE_TAG

#       # ---------------------------------------#

#       - name: Install Cosign
#         uses: sigstore/cosign-installer@v3.4.0

#       - name: Sign Frontend Image
#         env:
#           COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
#           COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
#           IMAGE_TAG: ${{ github.sha }}
#         run: |
#           cosign sign --yes --key env://COSIGN_PRIVATE_KEY $ECR_REGISTRY/$ECR_REPOSITORY:frontend-$IMAGE_TAG

# # ------------------------------------------------------#

#       - name: Update YAML and Push to GitHub
#         run: |
#           git config --global user.name "github-actions"
#           git config --global user.email "github-actions@github.com"
          
         
#           git pull origin main --rebase

          
#           sed -i "s/[0-9]\{12\}/${{ vars.AWS_ACCOUNT_ID }}/g" k8s/frontend.yaml
#           sed -i "s/frontend-[a-z0-9]*/frontend-${{ github.sha }}/g" k8s/frontend.yaml
          
#           git add k8s/frontend.yaml
         
#           git diff --quiet && git diff --staged --quiet || (git commit -m "Update frontend image to ${{ github.sha }}" && git push origin main)








name: Frontend CI/CD
on:
  push:
    paths:
      - 'frontend/**'        
      - 'k8s/**'              
      - '!k8s/frontend.yaml'
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # --- SonarCloud Scan ---
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v3
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Nabilaebrahim_fproject
            -Dsonar.organization=nabilaebrahim
            -Dsonar.sources=frontend/

      # --------------------------------------

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Frontend Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }} 
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:frontend-$IMAGE_TAG ./frontend
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:frontend-$IMAGE_TAG

      # ==========================================================
      #
      # ==========================================================
      - name: Get Secrets from AWS
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            prod/deployment/cosign

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.4.0

      # ==========================================================
      
      # ==========================================================
      - name: Sign Frontend Image
        env:
          # هنا بنجرب كل الاحتمالات لاسم المتغير عشان RAW_KEY ماتطلعش فاضية
          RAW_KEY: ${{ env.COSIGN_PRIVATE_KEY || env.PROD_DEPLOYMENT_COSIGN_COSIGN_PRIVATE_KEY || env.COSIGN_DATA_COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ env.COSIGN_PASSWORD || env.PROD_DEPLOYMENT_COSIGN_COSIGN_PASSWORD || env.COSIGN_DATA_COSIGN_PASSWORD }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          
          if [ -z "$RAW_KEY" ]; then 
            echo "❌ ERROR: RAW_KEY is EMPTY. Check AWS Secret keys names."
            exit 1
          fi

         
          printf "%b" "$RAW_KEY" > cosign.key

          echo "Checking Frontend key file format:"
          head -n 1 cosign.key

          
          cosign sign --yes --key cosign.key $ECR_REGISTRY/$ECR_REPOSITORY:frontend-$IMAGE_TAG
          
          
          rm cosign.key

      # ==========================================================

      - name: Update YAML and Push to GitHub
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          git pull origin main --rebase

          sed -i "s/[0-9]\{12\}/${{ vars.AWS_ACCOUNT_ID }}/g" k8s/frontend.yaml
          sed -i "s/frontend-[a-z0-9]*/frontend-${{ github.sha }}/g" k8s/frontend.yaml
          
          git add k8s/frontend.yaml
          
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update frontend image to ${{ github.sha }}" && git push origin main)